name: Deploy Lightning-Rod to Devnet

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version

      - name: Add Rust to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Anchor CLI 0.31.1
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install 0.31.1
          avm use 0.31.1
          anchor --version

      - name: Build Program
        run: anchor build

      - name: Deploy Program to Devnet
        run: anchor deploy
        env:
          ANCHOR_WALLET: ${{ secrets.ANCHOR_WALLET }}
